version: "3"
services:
  backend:
    build:
      context: ./backend  # Path to your backend directory
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend  # Path to your frontend directory
    ports:
      - "3000:3000"
